### ISSUE TITLE
Update plugin to Zotero 7

### ISSUE THREAD

**Issue by ForeverFloating** [volatile-static/zotero-inspector#1]
Is it possible to update the plugin to be compatible with Zotero 7?

**Comment by volatile-static** [comment]
No, it's not recommended. Zotero7 now provides built-in dev tool. So that this plugin can be deprecated.

**Comment by ForeverFloating** [comment]
How can I access the dev tools that inspect HTML elements in Zotero 7?

**Comment by volatile-static** [comment]
https://www.zotero.org/support/dev/zotero_7_for_developers
